services:
  observer:
    container_name: observer
    build:
      context: ./observer
    restart: unless-stopped
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - observer-net
    logging:
      driver: json-file
      options:
        max-size: "8m"
        max-file: "3"

  vector-aggregator:
    image: timberio/vector:0.48.0-alpine
    container_name: vector-aggregator
    restart: unless-stopped
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
    expose:
      - "8686"
    command: ["--config", "/etc/vector/vector.toml"]
    depends_on:
      - observer
    networks:
      - observer-net
    logging:
      driver: json-file
      options:
        max-size: "8m"
        max-file: "3"

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "7443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - vector-aggregator
    networks:
      - observer-net
    logging:
      driver: json-file
      options:
        max-size: "8m"
        max-file: "3"

  redis:
    image: redis:8.2-m01-alpine3.22
    container_name: redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - observer-net
    logging:
      driver: json-file
      options:
        max-size: "8m"
        max-file: "3"

networks:
  observer-net:
    driver: bridge

volumes:
  redis-data:
